project_id = "dxmxzuxpdxowuuollhtc"

[functions.ai-assistant]
verify_jwt = false

[functions.fetch-meta-campaigns]
verify_jwt = false

[functions.ai-trafego-analyst]
verify_jwt = false

[functions.kommo-webhook]
verify_jwt = false